version: '3'

services:
  apache:
    build: .
    container_name: php7-apache2
    restart: always
    command: >
      bash -c "a2enmod rewrite
      && apache2-foreground"
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    container_name: mysqlASW
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=consultorio